# Extend vert.x image
FROM vertx/vertx3

ENV VERTICLE_NAME com.guba.vertx.demo.MainApp
ENV VERTICLE_FILE target/demo*.jar

# Set the location of the verticles
ENV VERTICLE_HOME /usr/verticles

EXPOSE 8080

COPY $VERTICLE_FILE $VERTICLE_HOME/

# Launch the verticle
WORKDIR $VERTICLE_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec vertx run $VERTICLE_NAME -cp $VERTICLE_HOME/*"]