version: '3.8'

services:
  artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: artemis
    hostname: artemis
    environment:
      ENABLE_JMX_EXPORTER: "true"
      ARTEMIS_MIN_MEMORY: "1512M"
      ARTEMIS_MAX_MEMORY: "2000M"
      ARTEMIS_USER: "gubaguba"
      ARTEMIS_PASSWORD: "gubaguba"
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - artemis_instance:/var/lib/artemis-instance
    restart: unless-stopped

volumes:
  artemis_instance:
    name: artemis_instance
    driver: local
